name: music_channel_ios
description: YunShu Music For IOS
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  music_platform_interface:
    path: ../music_platform_interface
  just_audio: ^0.9.32
  shared_preferences: ^2.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    implements: music_channel
    platforms:
      ios:
        pluginClass: MusicChannelIosPlugin
        dartPluginClass: MusicChannelIos
