name: yunshu_music
description: YunShu Music
publish_to: 'none'
version: 1.3.3+58

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  music_channel:
    path: ../music_channel
  provider: ^6.1.5
  tuple: ^2.0.2
  dio: ^5.8.0+1
  flutter_app_minimizer_plus: ^1.0.2
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  audio_video_progress_bar: ^2.0.3
  url_launcher: ^6.3.1
  logger: ^2.5.0
  crypto: ^3.0.6
  path_provider: ^2.1.5
  mime_type: ^1.0.1
  package_info_plus: ^8.3.0
  flutter_update_dialog: ^2.0.0
  flutter_windowmanager_plus: ^1.0.1
  go_router: ^15.1.3
  windows_single_instance: ^1.0.1
  motion_toast: 2.14.0
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  msix: ^3.16.9

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asserts/icon/launcher_icon.png"

# flutter pub run msix:create
msix_config:
  display_name: 云舒音乐
  publisher_display_name: itning
  identity_name: top.itning.yunshumusic
  logo_path: ./asserts/icon/launcher_icon.png
  capabilities: musicLibrary, internetClient
  languages: zh-CN
  store: false
  architecture: x64

flutter:
  uses-material-design: true
  assets:
    - asserts/images/default_cover.jpg
    - asserts/icon/app_icon.ico
  fonts:
    # https://github.com/lxgw/LxgwWenKai/releases
    - family: LXGWWenKaiMono
      fonts:
        - asset: asserts/fonts/LXGWWenKaiMono-Regular.ttf
    - family: Roboto
      fonts:
        - asset: asserts/fonts/Roboto.ttf
