name: yunshu_music
description: YunShu Music
publish_to: 'none'
version: 1.1.38+38

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  music_channel:
    path: ../music_channel
  provider: ^6.0.5
  tuple: ^2.0.1
  dio: ^4.0.6
  move_to_background: ^1.0.2
  shared_preferences: ^2.0.16
  shimmer: ^2.0.0
  audio_video_progress_bar: ^0.11.0
  sqflite: ^2.2.3
  url_launcher: ^6.1.8
  fluttertoast: ^8.1.2
  logger: ^1.1.0
  crypto: ^3.0.2
  path_provider: ^2.0.12
  mime_type: ^1.0.0
  package_info_plus: ^3.0.2
  flutter_update_dialog: ^2.0.0
  flutter_windowmanager: ^0.2.0
  go_router: ^6.0.1
  windows_single_instance: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.11.0
  msix: ^3.7.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asserts/icon/launcher_icon.png"

# flutter pub run msix:create
msix_config:
  display_name: 云舒音乐
  publisher_display_name: itning
  identity_name: top.itning.yunshumusic
  logo_path: ./asserts/icon/launcher_icon.png
  capabilities: musicLibrary, internetClient
  languages: zh-CN
  store: false
  architecture: x64

flutter:
  uses-material-design: true
  assets:
    - asserts/images/default_cover.jpg
    - asserts/icon/app_icon.ico
  fonts:
    # https://github.com/lxgw/LxgwWenKai/releases
    - family: LXGWWenKaiMono
      fonts:
        - asset: asserts/fonts/LXGWWenKaiMono-Regular.ttf
    - family: Roboto
      fonts:
        - asset: asserts/fonts/Roboto.ttf
