# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "/yunshu_music"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/music_channel"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/music_channel_macos"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/music_channel_ios"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/music_channel_web"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/music_channel_windows"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/music_platform_interface"
    schedule:
      interval: "daily"
