name: Build and Deploy Flutter Web

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.32.8"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Get dependencies
        run: |
          cd yunshu_music
          flutter pub get

      - name: Build Flutter Web
        run: |
          cd yunshu_music
          flutter build web --release
          pwd && ls -la

      - name: Prepare deploy directory
        run: |
          mkdir -p deploy
          cp -r yunshu_music/build/web/. /home/runner/work/yunshu_music/deploy/
          pwd && ls -la

      - name: Checkout deploy branch
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: build_web

      - name: Clear old contents in deploy branch
        run: |
          pwd && ls -la
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git rm -rf . || echo "No files to remove."

      - name: Copy new build files
        run: |
          pwd && ls -la
          cp -r /home/runner/work/yunshu_music/deploy/. /home/runner/work/yunshu_music/yunshu_music

      - name: Commit and push changes
        run: |
          pwd && ls -la
          git add .
          git commit -m "Deploy web build" || echo "Nothing to commit"
          git push origin build_web --force
