name: macos_test

on:
  workflow_dispatch:
  
env:
  FLUTTER_VERSION: "3.32.6"
  
jobs:     
  build_mac_and_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          #channel: 'stable'
          cache: true

      - name: Restore packages
        run: |
          cd yunshu_music
          flutter pub get

      - name: Build Mac&IOS App
        run: |
          cd yunshu_music
          flutter build ios --release --no-codesign
          flutter build macos --release
          
      - name: Upload mac Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac
          path: yunshu_music/build/macos/Build/Products/Release

      - name: Upload ios Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios
          path: yunshu_music/build/ios/iphoneos
