name: msix_test

on:
  workflow_dispatch:
  
env:
  FLUTTER_VERSION: "3.32.3"
  
jobs:     
  build_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          #channel: 'stable'

      - name: Restore packages
        run: |
          cd yunshu_music
          flutter pub get

      - name: CERT
        run: |
          cd yunshu_music
          $certBytes = [System.Convert]::FromBase64String("${{ secrets.CERT_PFX_BASE64 }}")
          $pfxPath = Join-Path $(Get-Location) "yunshu_cert.pfx"
          [System.IO.File]::WriteAllBytes($pfxPath, $certBytes)

      - name: Build Windows App
        run: |
          cd yunshu_music
          dart run msix:create -c ./yunshu_cert.pfx -p ${{ secrets.CERT_PFX_PASSWORD }} --install-certificate false
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows_app
          path: yunshu_music/build/windows/x64/runner/Release/yunshu_music.msix
