name: Flutter Package

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
  
env:
  FLUTTER_VERSION: "3.0.2"
  
jobs:
  build_web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Restore packages
        run: |
          cd yunshu_music
          flutter pub get

      - name: Build Web App
        run: |
          cd yunshu_music
          flutter build web --web-renderer canvaskit --release
          
      - name: Zip
        uses: thedoctor0/zip-release@master
        with:
         filename: 'web.zip'
         path: 'yunshu_music/build/web'
         
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: web.zip
          if-no-files-found: error
         
  build_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup Java to compile Android project
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: Create the Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}
        run: |
          # import keystore from secrets
          cd yunshu_music
          ls -all
          echo $KEYSTORE_BASE64 | base64 -di > android/app/key.jks
          echo $KEY_PROPERTIES | base64 -di > android/key.properties

      - name: Restore packages
        run: |
          cd yunshu_music
          flutter pub get

      - name: Build Android App
        run: |
          cd yunshu_music
          flutter build apk --release --split-per-abi
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: yunshu_music/build/app/outputs/apk/release/*.apk
          if-no-files-found: error

  build_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Restore packages
        run: |
          cd yunshu_music
          flutter pub get

      - name: Build Windows App
        run: |
          cd yunshu_music
          flutter build windows --release
          Compress-Archive -Path .\build\windows\runner\Release\* -DestinationPath windows.zip
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: yunshu_music\windows.zip
          if-no-files-found: error
