name: music_channel_web
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

flutter:
  plugin:
    implements: music_channel
    platforms:
      web:
        pluginClass: MusicChannel
        fileName: music_channel_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  music_platform_interface:
    path: ../music_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4


